### ISSUE TITLE
String Enums cannot be directly used in mavlink commands

### ISSUE THREAD

**Issue by rafaellehmkuhl** [patrickelectric/mavlink2rest-ts#2]
Enums like the [MotorTestThrottleType](https://github.com/patrickelectric/mavlink2rest-ts/blob/ae881c760bb37b553e70c1923253b19b8fbe44b6/messages/mavlink2rest-enum.ts#L1817) are used in the context of command-long messages. As this kind of message expects a number, and not a string, it cannot be directly used with it.

My suggestion would be that they have the same value as they have [in the Mavlink protocol](https://mavlink.io/en/messages/common.html#MOTOR_TEST_THROTTLE_TYPE), so they can be directly used.

**Comment by joaoantoniocardoso** [comment]
@patrickelectric This is the issue I'll attack now

**Comment by rafaellehmkuhl** [comment]
> @patrickelectric This is the issue I'll attack now

Much love.

**Comment by rafaellehmkuhl** [comment]
> We've chosen to keep the enums as strings and only change the Flags to numbers because the mavlink2rest on BlueOS is heavily using them as strings already. (#5)
> 
> Should we create another file with the enums as values instead of strings? @rafaellehmkuhl @patrickelectric
> 
> Either way, this issue should be reopened.

Without the numbers we cannot talk to the autopilot and we will keep a lot of hardcoded numbers along the code, as we currently have already.

I didn't get what the "Flags" are. I can use them somehow knowing the Enum?
